# @package _global_

defaults:
  - legged_base

# Env structure
env:
  _target_: humanoidverse.envs.motion_tracking.asap.asap.ASAPMotion
  config:
    max_episode_length_s: 20
    termination:
      terminate_by_contact: False
      terminate_by_gravity: True
      terminate_by_low_height: False
      time_out_when_motion_end: True   # update for time out
      terminate_when_motion_far: False
      terminate_when_close_to_dof_pos_limit: False
      terminate_when_close_to_dof_vel_limit: False
      terminate_when_close_to_torque_limit: False
    termination_scales:
      termination_min_base_height : 0.2
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8
      termination_motion_far_threshold : 1.5
      termination_close_to_dof_pos_limit : 0.98
      termination_close_to_dof_vel_limit : 0.98
      termination_close_to_torque_limit : 0.98
    termination_probality:
      terminate_when_close_to_dof_pos_limit: 0.25
      terminate_when_close_to_dof_vel_limit: 0.25
      terminate_when_close_to_torque_limit: 0.25
    termination_curriculum:
      terminate_when_motion_far_curriculum: False
      terminate_when_motion_far_initial_threshold: 1.5
      terminate_when_motion_far_threshold_max: 2.0
      terminate_when_motion_far_threshold_min: 0.25
      terminate_when_motion_far_curriculum_degree: 0.0000025
      terminate_when_motion_far_curriculum_level_down_threshold: 40
      terminate_when_motion_far_curriculum_level_up_threshold: 42

    resample_motion_when_training: True
    resample_time_interval_s: 2000

    noise_to_initial_level: 0
    init_noise_scale:
      dof_pos: 0.1
      dof_vel: 0.15
      root_pos: 0.05
      root_rot: 10 # degree, * 3.14 / 180
      root_vel: 0.01
      root_ang_vel: 0.01

    use_teleop_control: False
    enforce_randomize_motion_start_eval: False


# Globally accessible parameters
log_task_name: motion_tracking

eval_overrides:
  env:
    config:
      max_episode_length_s: 100000
