# @package _global_

# Be careful when using _raw, history
obs:
  obs_dict:
    actor_obs: [
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      dof_pos,
      dof_vel,
      actions,
      ref_motion_phase
      # dif_local_rigid_body_pos,
      # local_ref_rigid_body_pos,
      # history,
    ]

    critic_obs: [
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      dof_pos,
      dof_vel,
      actions,
      ref_motion_phase
      # dif_local_rigid_body_pos,
      # local_ref_rigid_body_pos,
    ]

  obs_auxiliary: # define those coumpounds in obs_dict, for example, you can define different long/short history with different length
    history: {
      dof_pos: 5,
      dof_vel: 5,
      actions: 5,
    }

  obs_scales: {
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    history: 1.0,
    actions: 1.0,
    dif_local_rigid_body_pos: 1.0,
    local_ref_rigid_body_pos: 1.0,
    ref_motion_phase: 1.0,
  }

  noise_scales: {
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    projected_gravity: 0.0,
    dof_pos: 0.0,
    dof_vel: 0.0,
    actions: 0.0,
    history: 0.0,
    dif_local_rigid_body_pos: 0.0,
    local_ref_rigid_body_pos: 0.0,
    ref_motion_phase: 0.0,
  }

  obs_dims:
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size}
    - dif_local_rigid_body_pos: ${eval:'3 * ${robot.num_bodies} + 9'} # hardcoded for 3 extended body
    - local_ref_rigid_body_pos: ${eval:'3 * ${robot.num_bodies} + 9'}
    - ref_motion_phase: 1

  post_compute_config: {} # Will store values after preprocessing, don't put anything here